# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sampling_time',
            field=models.IntegerField(default=1),
        ),
    ]
