# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sensor_sampling_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_family_id',
            new_name='sensor_family',
        ),
    ]
